# RaPiSys — ARM64-first multi-stage build (works on amd64 too)
FROM node:22-alpine AS builder

WORKDIR /app

# Native build tools for better-sqlite3 (falls back to node:sqlite if absent)
RUN apk add --no-cache python3 make g++

COPY package*.json ./
RUN npm ci

COPY server/ ./server/
COPY src/ ./src/
COPY vite.config.js ./

RUN npm run build

# ---------------- Production stage ----------------
FROM node:22-alpine

WORKDIR /app

# Tools for systeminformation, network stats, WireGuard
RUN apk add --no-cache procps util-linux iproute2 wireguard-tools

COPY package*.json ./
RUN apk add --no-cache --virtual .build python3 make g++ \
 && npm ci --omit=dev \
 && apk del .build

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/server ./server

# Default settings config
COPY settings.json ./settings.json

# Run as non-root: privileged work happens in the host agent, not here.
RUN addgroup -g 990 rapisys && adduser -D -G rapisys -u 990 rapisys \
 && mkdir -p /app/data && chown -R rapisys:rapisys /app
USER rapisys

# ===================
# Environment
# ===================
ENV PORT=3001
ENV ADMIN_TOKEN=
ENV CORS_ORIGINS=*
ENV SETTINGS_CONFIG=/app/data/settings.json
ENV DATA_DIR=/app/data
# 64-hex-char key for secrets-at-rest (generated by deploy.sh)
ENV SECRET_KEY=
# Host agent socket + shared secret (set by deploy.sh)
ENV AGENT_SOCKET=/run/rapisys/agent.sock
ENV AGENT_SECRET=
# Metrics sampling cadence (seconds)
ENV SAMPLE_INTERVAL_S=10

EXPOSE 3001

CMD ["node", "server/index.js"]
