/** RaPiSys — routing the Pi's own DNS through Pi-hole via NetworkManager.
 *
 * On Raspberry Pi OS, /etc/resolv.conf is written by NetworkManager, so the
 * agent sets DNS on the NM connections instead. Fixture: `nmcli -t -f
 * DEVICE,TYPE,STATE,CON-UUID,CONNECTION device status` on XRPi, 2026-10-09
 * (eth0 + Wi-Fi up, Tailscale, Docker bridges and veths alongside).
 */
import { describe, it, expect } from 'vitest';
import { createRequire } from 'module';

const require = createRequire(import.meta.url);
process.env.AGENT_SECRET = 'test-secret-not-used-for-any-real-hmac';
const { nmcliFields, nmDnsTargets, firstNameserver, nameservers, piholeResolvers } = require('../agent/rapisys-agent.cjs');
const { peerDnsCandidates, labelResolvers } = await import('../server/routes/network.js');

const XRPI_DEVICES = [
  'eth0:ethernet:connected:75a1216a-9d1a-30cd-8aca-ace5526ec021:netplan-eth0',
  'wlan0:wifi:connected:c89acdb3-496f-3c43-a3fa-3f4aea8a17d7:netplan-wlan0-HomeNet',
  'tailscale0:tun:connected (externally):1052cd60-469f-44fd-a79f-c1881c2cd6f1:tailscale0',
  'br-3263731d90ef:bridge:connected (externally):2d35de46-4385-4af7-b63f-f66da0bce696:br-3263731d90ef',
  'docker0:bridge:connected (externally):9914df4c-2c29-41d2-85f7-3c87ced6b40a:docker0',
  'lo:loopback:connected (externally):971a49f0-197a-43f1-a36d-88ac38b626ee:lo',
  'veth1064616:ethernet:connected (externally):03861c34-d5a2-4bbe-9af8-389f0caf9e9b:veth1064616',
  'p2p-dev-wlan0:wifi-p2p:disconnected::',
].join('\n') + '\n';

describe('nmDnsTargets', () => {
  it('picks the Ethernet and Wi-Fi connections NM brought up', () => {
    expect(nmDnsTargets(XRPI_DEVICES)).toEqual([
      { device: 'eth0', type: 'ethernet', uuid: '75a1216a-9d1a-30cd-8aca-ace5526ec021', name: 'netplan-eth0' },
      { device: 'wlan0', type: 'wifi', uuid: 'c89acdb3-496f-3c43-a3fa-3f4aea8a17d7', name: 'netplan-wlan0-HomeNet' },
    ]);
  });

  it('skips Docker veths, bridges, Tailscale and loopback', () => {
    const devices = nmDnsTargets(XRPI_DEVICES).map((t) => t.device);
    for (const d of ['veth1064616', 'docker0', 'br-3263731d90ef', 'tailscale0', 'lo']) expect(devices).not.toContain(d);
  });

  it('skips connecting / disconnected devices and empty output', () => {
    expect(nmDnsTargets('eth0:ethernet:connecting (getting IP configuration):u1:Wired\nwlan0:wifi:disconnected::\n')).toEqual([]);
    expect(nmDnsTargets('')).toEqual([]);
  });

  it('keeps connection names that contain an escaped colon', () => {
    const [t] = nmDnsTargets('wlan0:wifi:connected:u-1:Cafe\\: Guest\n');
    expect(t).toEqual({ device: 'wlan0', type: 'wifi', uuid: 'u-1', name: 'Cafe: Guest' });
  });
});

describe('nmcliFields', () => {
  it('splits on unescaped colons and unescapes', () => {
    expect(nmcliFields('a:b\\:c:d\\\\e')).toEqual(['a', 'b:c', 'd\\e']);
    expect(nmcliFields('x::')).toEqual(['x', '', '']);
  });
});

describe('firstNameserver', () => {
  it('reads the resolver the Pi actually uses', () => {
    expect(firstNameserver('# Generated by NetworkManager\nnameserver 192.168.10.1\n')).toBe('192.168.10.1');
    expect(firstNameserver('# Generated by NetworkManager\noptions timeout:2 attempts:2\nnameserver 127.0.0.1\nnameserver 1.1.1.1\n')).toBe('127.0.0.1');
    expect(firstNameserver('# empty\n')).toBeNull();
  });
});

describe('piholeResolvers', () => {
  it('orders this Pi, the other Pi-hole, then public DNS', () => {
    expect(piholeResolvers('10.0.0.12', '1.1.1.1')).toEqual(['127.0.0.1', '10.0.0.12', '1.1.1.1']);
  });
  it('falls back to public DNS alone when no other Pi-hole answers', () => {
    expect(piholeResolvers(null, '1.1.1.1')).toEqual(['127.0.0.1', '1.1.1.1']);
  });
  it('never repeats a server and never exceeds the three glibc uses', () => {
    expect(piholeResolvers('1.1.1.1', '1.1.1.1')).toEqual(['127.0.0.1', '1.1.1.1']);
    expect(piholeResolvers(null, null)).toEqual(['127.0.0.1']);
  });
});

describe('nameservers', () => {
  it('lists every nameserver in order', () => {
    expect(nameservers('# Generated by NetworkManager\nnameserver 127.0.0.1\nnameserver 10.0.0.12\nnameserver 1.1.1.1\noptions timeout:2\n'))
      .toEqual(['127.0.0.1', '10.0.0.12', '1.1.1.1']);
  });
});

describe('peer DNS fallback candidates', () => {
  const peers = [
    { name: 'YRPi', baseUrl: 'https://10.0.0.12:3443', enabled: true },
    { name: 'Off', baseUrl: 'https://10.0.0.20:3443', enabled: false },
    { name: 'ByName', baseUrl: 'https://zpi.local:3443', enabled: true },
    { name: 'Broken', baseUrl: 'not a url', enabled: true },
  ];
  it('keeps enabled peers addressed by an IPv4', () => {
    expect(peerDnsCandidates(peers)).toEqual([{ name: 'YRPi', ip: '10.0.0.12' }]);
  });
  it('labels this Pi, named nodes, and public servers', () => {
    expect(labelResolvers(['127.0.0.1', '10.0.0.12', '1.1.1.1'], peerDnsCandidates(peers))).toEqual([
      { ip: '127.0.0.1', name: 'this Pi' }, { ip: '10.0.0.12', name: 'YRPi' }, { ip: '1.1.1.1', name: null },
    ]);
  });
});
