/**
 * RaPiSys — Secrets-at-rest helper (AES-256-GCM)
 * ----------------------------------------------
 * Encrypts sensitive settings (SMTP password, NAS credentials) before they
 * are stored in SQLite. The key comes from the SECRET_KEY environment
 * variable (a 64-char hex string generated by deploy.sh). Without a key the
 * helpers throw, so secrets can never be silently stored in plaintext.
 */

import crypto from 'crypto';

function keyFromEnv() {
  const hex = process.env.SECRET_KEY || '';
  if (!/^[0-9a-fA-F]{64}$/.test(hex)) {
    throw new Error('SECRET_KEY env var must be 64 hex chars (openssl rand -hex 32)');
  }
  return Buffer.from(hex, 'hex');
}

export function hasSecretKey() {
  return /^[0-9a-fA-F]{64}$/.test(process.env.SECRET_KEY || '');
}

export function encrypt(plaintext) {
  const key = keyFromEnv();
  const iv = crypto.randomBytes(12);
  const cipher = crypto.createCipheriv('aes-256-gcm', key, iv);
  const ciphertext = Buffer.concat([cipher.update(String(plaintext), 'utf-8'), cipher.final()]);
  return { ciphertext, iv, tag: cipher.getAuthTag() };
}

export function decrypt({ ciphertext, iv, tag }) {
  const key = keyFromEnv();
  const decipher = crypto.createDecipheriv('aes-256-gcm', key, Buffer.from(iv));
  decipher.setAuthTag(Buffer.from(tag));
  return Buffer.concat([decipher.update(Buffer.from(ciphertext)), decipher.final()]).toString('utf-8');
}
